version: '3.8'

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/wellness_app}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN:-http://localhost}
    depends_on:
      - mongo
    networks:
      - app

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mongo_data:
